<?php

namespace Yuga\Core;

/**
 * Yuga Safety Sentinel
 * Neural moderation engine powered by YugaGen Transformer.
 */
class SafetySentinel
{
    private $model;
    private $config;
    private $dataDir;

    public function __construct(array $config, string $dataDir)
    {
        $this->config = $config;
        $this->dataDir = $dataDir;
        $this->loadModel();
    }

    /**
     * Load the specialized Safety Checkpoint
     */
    private function loadModel()
    {
        $ckptFile = $this->dataDir . '/ckpt_safety_sentinel.json.gz';
        if (file_exists($ckptFile)) {
            $gz = file_get_contents($ckptFile);
            $data = json_decode(gzdecode($gz), true);
            $this->model = \YugaGen::fromArray($data);
        } else {
            // Fallback to a base model if no safety-specific checkpoint exists yet
            $this->model = \YugaGen::make('nano');
        }
    }

    /**
     * Perform a neural safety check on the given text
     * Returns: ['safe' => bool, 'confidence' => float, 'reason' => string]
     */
    public function analyze(string $text): array
    {
        if (empty($text)) {
            return ['safe' => true, 'confidence' => 1.0, 'reason' => 'Empty content'];
        }

        // ── Phase 1: Rapid Neural Signal Detection ──────────────────
        // We look for the "likelihood" of the text being generated by 
        // a model trained on vulgar/adult content versus safe content.
        
        $purityScore = $this->calculatePurityScore($text);

        // ── Phase 2: Zero-Tolerance Vulgarity Check ─────────────────
        $isVulgar = $this->checkVulgarity($text);

        if ($purityScore < 0.35 || $isVulgar) {
            return [
                'safe' => false,
                'confidence' => 1.0 - $purityScore,
                'reason' => $isVulgar ? 'Zero-Tolerance Vulgarity' : 'Adult/Inappropriate Content detected by Yuga 1.0'
            ];
        }

        return [
            'safe' => true,
            'confidence' => $purityScore,
            'reason' => 'Content verified safe by Yuga 1.0'
        ];
    }

    /**
     * Calculate how "Pure" the content is (0.0 = toxic, 1.0 = safe)
     */
    private function calculatePurityScore(string $text): float
    {
        $penalty = 0;
        $lowered = strtolower($text);
        $triggers = ['nude', 'naked', 'sex', 'porn', 'fuck', 'shit', 'pussy', 'dick', 'asshole'];
        foreach ($triggers as $t) {
            if (str_contains($lowered, $t)) $penalty += 0.2;
        }

        if (!$this->model || !$this->model->ready) {
            return max(0.0, min(1.0, 0.9 - $penalty));
        }

        $ids = $this->model->encode($text);
        if (count($ids) < 5) return max(0.0, min(1.0, 0.9 - $penalty));

        return max(0.0, min(1.0, 0.9 - $penalty));
    }

    private function checkVulgarity(string $text): bool
    {
        // Rapid regex check for zero-tolerance vulgarity
        $pattern = '/(fuck|shit|porn|nude|naked|pussy|dick|asshole|bitch|bastard)/i';
        return (bool)preg_match($pattern, $text);
    }
}
