<?php
/**
 * Yuga Setup Wizard
 * Run once: https://yoursite.com/yuga/install.php
 * DELETE this file after installation.
 */
session_start();

define('YUGA_ROOT', __DIR__);
$data_dir   = __DIR__ . '/data';
$config_file = __DIR__ . '/config.php';
$host       = (isset($_SERVER['HTTPS']) ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'];
$base       = rtrim(dirname($_SERVER['SCRIPT_NAME']), '/');
$admin_url  = $host . $base . '/admin/';
$api_url    = $host . $base . '/api/';
$portal_url = $host . $base . '/portal/';
$widget_url = $host . $base . '/widget/yuga-widget.js';

// ── CSRF ────────────────────────────────────────────────────────────────
if (empty($_SESSION['install_csrf'])) {
    $_SESSION['install_csrf'] = bin2hex(random_bytes(32));
}
$csrf = $_SESSION['install_csrf'];

// ── Step logic ──────────────────────────────────────────────────────────
// step 1 = env check, step 2 = config form, step 3 = done
$step  = (int)($_SESSION['install_step'] ?? 1);
$error = '';

// ── Handle POST: save config ────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['act'] ?? '') === 'save_config') {
    if (($_POST['_csrf'] ?? '') !== $csrf) die('Invalid CSRF token.');

    $pw    = trim($_POST['admin_password'] ?? '');
    $ak    = trim($_POST['api_key'] ?? '');
    $email = trim($_POST['from_email'] ?? '');
    $slug  = preg_replace('/[^a-z0-9\-]/', '', strtolower(trim($_POST['admin_slug'] ?? 'admin'))) ?: 'admin';

    if (strlen($pw) < 8) {
        $error = 'Admin password must be at least 8 characters.';
        $step  = 2;
    } elseif (strlen($ak) < 8) {
        $error = 'API key must be at least 8 characters.';
        $step  = 2;
    } elseif (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        $error = 'Please enter a valid from-email address.';
        $step  = 2;
    } else {
        // Build config array
        $cfg = [
            'admin_password'    => $pw,
            'api_key'           => $ak,
            'default_model'     => 'default',
            'llm_backend'       => trim($_POST['llm_backend'] ?? 'claude'),
            'anthropic_api_key' => trim($_POST['anthropic_api_key'] ?? ''),
            'openai_api_key'    => trim($_POST['openai_api_key'] ?? ''),
            'ollama_url'        => trim($_POST['ollama_url'] ?? 'http://localhost:11434'),
            'ollama_model'      => 'llama3.2',
            'admin_slug'        => $slug,
            'assistant_name'    => trim($_POST['assistant_name'] ?? 'AI Assistant'),
            'platform_name'     => trim($_POST['platform_name'] ?? 'our platform'),
            'site_url'          => $host . $base,
            'site_description'  => trim($_POST['site_description'] ?? ''),
            'tone'              => 'helpful and friendly',
            'auto_learn'        => true,
            'max_pages'         => 50,
            'train_steps'       => 15000,
            'time_limit'        => 300,
            'memory_limit'      => '128M',
            'stripe' => [
                'test_mode'      => true,
                'secret_key'     => trim($_POST['stripe_key'] ?? ''),
                'webhook_secret' => '',
            ],
            'paypal' => [
                'test_mode'     => true,
                'client_id'     => trim($_POST['paypal_id'] ?? ''),
                'client_secret' => trim($_POST['paypal_secret'] ?? ''),
            ],
            'mail' => [
                'from_email' => $email,
                'from_name'  => trim($_POST['from_name'] ?? 'Yuga'),
                'portal_url' => $portal_url,
                'smtp' => [
                    'host'     => trim($_POST['smtp_host'] ?? ''),
                    'port'     => (int)($_POST['smtp_port'] ?? 587),
                    'username' => trim($_POST['smtp_user'] ?? ''),
                    'password' => trim($_POST['smtp_pass'] ?? ''),
                ],
            ],
            'usd_to_npr_rate' => 133.5,
            'esewa'   => ['test_mode'=>true,'merchant_code'=>'EPAYTEST','secret_key'=>''],
            'fonepay' => ['test_mode'=>true,'merchant_id'=>'NBQM','secret_key'=>''],
            'imepay'  => ['test_mode'=>true,'merchant_code'=>'','merchant_name'=>'Yuga','module'=>'','username'=>'','password'=>''],
        ];

        // Write config.php
        $lines = "<?php\n/**\n * Yuga Configuration — generated by installer\n */\nreturn " . var_export($cfg, true) . ";\n";
        if (file_put_contents($config_file, $lines) === false) {
            $error = 'Could not write config.php — check file permissions on the root directory.';
            $step  = 2;
        } else {
            // Create default model
            if (is_writable($data_dir)) {
                require_once __DIR__ . '/core/YugaLM.php';
                require_once __DIR__ . '/core/ModelStore.php';
                $store = new ModelStore($data_dir);
                if (!$store->loadModel('default')) {
                    $m = new YugaLM();
                    $store->saveModel('default', $m->save());
                }
            }
            // ── Write .htaccess dynamic admin URL rules ────────────────
            $htaccess_file = __DIR__ . '/.htaccess';
            $htaccess = file_exists($htaccess_file) ? file_get_contents($htaccess_file) : '';
            // Remove any previous dynamic admin block
            $htaccess = preg_replace('/# \[YUGA-ADMIN-SLUG\].*?# \[\/YUGA-ADMIN-SLUG\]\n?/s', '', $htaccess);
            if ($slug !== 'admin') {
                $admin_rules = "# [YUGA-ADMIN-SLUG]\n"
                    . "<IfModule mod_rewrite.c>\n"
                    . "    # Block direct /admin/ access — use custom slug below\n"
                    . "    RewriteRule ^admin/?$ - [F,L]\n"
                    . "    RewriteRule ^admin/(.+)$ - [F,L]\n"
                    . "    # Route custom admin slug to admin/\n"
                    . "    RewriteRule ^{$slug}/?$ admin/index.php [QSA,L]\n"
                    . "    RewriteRule ^{$slug}/(.*)$ admin/$1 [QSA,L]\n"
                    . "</IfModule>\n"
                    . "# [/YUGA-ADMIN-SLUG]\n";
                // Insert after the first RewriteEngine On line
                if (str_contains($htaccess, 'RewriteEngine On')) {
                    $htaccess = str_replace("RewriteEngine On\n", "RewriteEngine On\n\n" . $admin_rules, $htaccess);
                } else {
                    $htaccess .= "\n" . $admin_rules;
                }
                file_put_contents($htaccess_file, $htaccess);
            }
            // ── Write robots.txt ───────────────────────────────────────
            $robots = "User-agent: *\n"
                . "Allow: /\n"
                . "Disallow: /data/\n"
                . "Disallow: /admin/\n"
                . ($slug !== 'admin' ? "Disallow: /{$slug}/\n" : '')
                . "Disallow: /update/\n"
                . "Disallow: /scheduler/\n"
                . "Sitemap: {$host}{$base}/sitemap.php\n";
            file_put_contents(__DIR__ . '/robots.txt', $robots);
            // ── Write llms.txt (AI SEO) ────────────────────────────────
            $platform = trim($_POST['platform_name'] ?? 'Yuga Platform');
            $desc     = trim($_POST['site_description'] ?? 'A self-learning AI assistant platform built on pure PHP.');
            $llms = "# {$platform}\n"
                . "> {$desc}\n\n"
                . "## What is this?\n"
                . "{$platform} is powered by Yuga — a self-learning small language model that runs entirely on PHP shared hosting. "
                . "It learns from your content and answers questions about it.\n\n"
                . "## API\n"
                . "REST JSON API available at: {$host}{$base}/api/\n"
                . "Documentation: {$host}{$base}/portal/?page=docs\n\n"
                . "## Pricing\n"
                . "Plans available at: {$host}{$base}/portal/?page=pricing\n\n"
                . "## Contact / Signup\n"
                . "Get an API key: {$host}{$base}/portal/\n\n"
                . "## Content Policy\n"
                . "This AI is trained on content from {$platform}. Responses are grounded in that content.\n\n"
                . "## Instructions for AI crawlers\n"
                . "You may index the portal, docs, and pricing pages.\n"
                . "Do not index /data/, /admin/, /update/, or /scheduler/ paths.\n";
            file_put_contents(__DIR__ . '/llms.txt', $llms);
            $_SESSION['install_step'] = 3;
            $_SESSION['install_slug'] = $slug;
            $step = 3;
        }
    }
}

// ── Handle POST: advance step 1 → 2 ────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['act'] ?? '') === 'next') {
    if (($_POST['_csrf'] ?? '') !== $csrf) die('Invalid CSRF token.');
    $_SESSION['install_step'] = 2;
    $step = 2;
}

// ── Env checks (used on step 1) ─────────────────────────────────────────
$checks = [];
if (!is_dir($data_dir)) @mkdir($data_dir, 0755, true);
$writable = is_writable($data_dir);
$checks[] = ['PHP ≥ 7.4',        version_compare(PHP_VERSION, '7.4.0', '>='), 'Upgrade PHP to 7.4+'];
$checks[] = ['data/ writable',   $writable,                                   'chmod 755 data/  (or create it via File Manager and set permissions)'];
$checks[] = ['cURL extension',   function_exists('curl_init'),                'Enable cURL in PHP settings'];
$checks[] = ['SQLite extension',  extension_loaded('sqlite3')||extension_loaded('pdo_sqlite'), 'Enable sqlite3 in PHP settings (JSON fallback will be used otherwise)'];
$checks[] = ['core/YugaLM.php',  file_exists(__DIR__.'/core/YugaLM.php'),     'Upload the core/ folder'];
$checks[] = ['api/index.php',    file_exists(__DIR__.'/api/index.php'),        'Upload the api/ folder'];
$checks[] = ['Memory ≥ 64M',     (function(){ $m=ini_get('memory_limit'); return (str_contains($m,'G')?((int)$m*1024):(int)$m) >= 64; })(), 'Add php_value memory_limit 128M to .htaccess'];
$checks[] = ['config.php writable', (!file_exists($config_file) || is_writable($config_file)), 'chmod 644 config.php or check FTP permissions'];

$all_pass = !in_array(false, array_column($checks, 1));
$critical_fail = !$writable || !file_exists(__DIR__.'/core/YugaLM.php');
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Yuga Setup Wizard</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:system-ui,sans-serif;background:#0a0f1e;color:#e2e8f0;min-height:100vh;padding:40px 20px}
.wrap{max-width:680px;margin:0 auto}
h1{font-size:28px;background:linear-gradient(135deg,#6366f1,#8b5cf6);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:4px}
.sub{color:#475569;font-size:14px;margin-bottom:32px}
/* Steps */
.steps{display:flex;gap:0;margin-bottom:36px}
.st{flex:1;text-align:center;font-size:12px;font-weight:600;padding:10px 4px;border-bottom:3px solid #1e293b;color:#475569;transition:.2s}
.st.done{border-color:#10b981;color:#6ee7b7}
.st.active{border-color:#6366f1;color:#a5b4fc}
/* Checks */
.chk{display:flex;align-items:flex-start;gap:10px;padding:10px 0;border-bottom:1px solid #1e293b;font-size:14px}
.chk:last-child{border:none}
.fix{font-size:12px;color:#f59e0b;margin-top:3px}
/* Cards */
.card{background:#0d1526;border:1px solid #1e293b;border-radius:14px;padding:24px;margin-bottom:20px}
.card-title{font-size:13px;font-weight:600;color:#a5b4fc;margin-bottom:16px;text-transform:uppercase;letter-spacing:.06em}
/* Form */
.fg{margin-bottom:14px}
.fg label{display:block;font-size:12px;color:#64748b;font-weight:600;margin-bottom:5px}
.fg input,select{width:100%;background:#111827;border:1px solid #334155;border-radius:8px;padding:9px 12px;color:#e2e8f0;font-size:13px;outline:none}
.fg input:focus,select:focus{border-color:#6366f1}
.fg .hint{font-size:11px;color:#475569;margin-top:4px}
.fr{display:grid;grid-template-columns:1fr 1fr;gap:12px}
/* Buttons */
.btn{border:none;border-radius:8px;padding:11px 22px;font-size:14px;font-weight:700;cursor:pointer;transition:.15s;display:inline-block;text-decoration:none}
.bp{background:#6366f1;color:#fff}.bp:hover{background:#4f46e5}
.bs{background:transparent;border:1px solid #334155;color:#94a3b8;padding:9px 18px;font-size:13px}
.bs:hover{border-color:#6366f1;color:#a5b4fc}
/* Alert */
.err{background:rgba(239,68,68,.1);border:1px solid #ef4444;border-radius:8px;padding:11px 14px;font-size:13px;color:#fca5a5;margin-bottom:18px}
.warn{background:rgba(245,158,11,.08);border:1px solid rgba(245,158,11,.3);border-radius:8px;padding:11px 14px;font-size:13px;color:#fcd34d;margin-bottom:18px}
/* Success */
.big-ok{font-size:52px;margin-bottom:8px;text-align:center}
.url-box{background:#111827;border:1px solid #1e293b;border-radius:8px;padding:11px 14px;font-size:13px;font-family:monospace;color:#14b8a6;word-break:break-all;margin-bottom:8px}
.pill{display:inline-block;padding:2px 9px;border-radius:20px;font-size:11px;font-weight:500}
.pg{background:rgba(16,185,129,.15);color:#6ee7b7}.pr{background:rgba(239,68,68,.15);color:#fca5a5}
.secret-toggle{cursor:pointer;user-select:none;color:#475569;font-size:12px;margin-left:6px}
</style>
</head>
<body>
<div class="wrap">
<h1>🧠 Yuga Setup Wizard</h1>
<p class="sub">Configure and install Yuga on your server — no file editing required.</p>

<!-- Step indicator -->
<div class="steps">
  <div class="st <?= $step >= 1 ? ($step > 1 ? 'done' : 'active') : '' ?>">1 — Environment</div>
  <div class="st <?= $step >= 2 ? ($step > 2 ? 'done' : 'active') : '' ?>">2 — Configuration</div>
  <div class="st <?= $step >= 3 ? 'done active' : '' ?>">3 — Done</div>
</div>

<?php if ($error): ?>
<div class="err"><?= htmlspecialchars($error) ?></div>
<?php endif; ?>

<!-- ═══════════════════════════════════════════════════════ STEP 1 -->
<?php if ($step === 1): ?>
<div class="card">
  <div class="card-title">Environment checks</div>
  <?php foreach ($checks as [$label, $ok, $fix]): ?>
  <div class="chk">
    <span><?= $ok ? '✅' : '⚠️' ?></span>
    <div>
      <div><?= htmlspecialchars($label) ?></div>
      <?php if (!$ok): ?><div class="fix">Fix: <?= htmlspecialchars($fix) ?></div><?php endif; ?>
    </div>
  </div>
  <?php endforeach; ?>
</div>

<?php if ($critical_fail): ?>
<div class="warn">Critical checks failed. Fix them before continuing.</div>
<form method="POST">
  <input type="hidden" name="_csrf" value="<?= $csrf ?>">
  <button type="submit" name="act" value="next" class="btn bp" disabled style="opacity:.4;cursor:not-allowed">Fix issues above first</button>
  &nbsp;<a href="<?= htmlspecialchars($_SERVER['SCRIPT_NAME']) ?>" class="btn bs">Re-check</a>
</form>
<?php else: ?>
<?php if (!$all_pass): ?>
<div class="warn">Some optional checks failed — you can continue, but fix them for best performance.</div>
<?php endif; ?>
<form method="POST">
  <input type="hidden" name="_csrf" value="<?= $csrf ?>">
  <button type="submit" name="act" value="next" class="btn bp">Continue to Configuration →</button>
</form>
<?php endif; ?>

<!-- ═══════════════════════════════════════════════════════ STEP 2 -->
<?php elseif ($step === 2): ?>
<form method="POST">
<input type="hidden" name="_csrf" value="<?= $csrf ?>">
<input type="hidden" name="act" value="save_config">

<div class="card">
  <div class="card-title">Security</div>
  <div class="fr">
    <div class="fg">
      <label>Admin password <span style="color:#ef4444">*</span></label>
      <input type="password" name="admin_password" id="apw" required minlength="8" placeholder="Min 8 characters">
      <div class="hint">Used to log in to the admin panel. <span class="secret-toggle" onclick="tog('apw')">show</span></div>
    </div>
    <div class="fg">
      <label>API key <span style="color:#ef4444">*</span></label>
      <input type="password" name="api_key" id="akey" required minlength="8" placeholder="Random secret string"
             value="<?= htmlspecialchars(bin2hex(random_bytes(12))) ?>">
      <div class="hint">Protects your API endpoint. <span class="secret-toggle" onclick="tog('akey')">show</span></div>
    </div>
  </div>
  <div class="fg">
    <label>Admin panel URL slug</label>
    <div style="display:flex;align-items:center;gap:8px">
      <span style="color:var(--di);font-size:13px">yourdomain.com/yuga/</span>
      <input type="text" name="admin_slug" value="admin" placeholder="admin" pattern="[a-z0-9\-]+" style="max-width:200px">
    </div>
    <div class="hint">Change to something secret like <code>my-panel-x7k</code> to hide the admin URL from bots. Only lowercase letters, numbers, hyphens.</div>
  </div>
</div>

<div class="card">
  <div class="card-title">Site identity &amp; SEO</div>
  <div class="fr">
    <div class="fg">
      <label>Platform / company name</label>
      <input type="text" name="platform_name" value="Yuga AI" placeholder="e.g. Acme Corp">
      <div class="hint">Used in page titles, emails, SEO tags</div>
    </div>
    <div class="fg">
      <label>Assistant name</label>
      <input type="text" name="assistant_name" value="AI Assistant" placeholder="e.g. Aria">
      <div class="hint">Shown in chat widget + Telegram/WhatsApp</div>
    </div>
  </div>
  <div class="fg">
    <label>Site description <span style="color:#64748b">(for SEO &amp; AI crawlers)</span></label>
    <input type="text" name="site_description" placeholder="e.g. Private AI assistant trained on your business knowledge — no cloud required.">
    <div class="hint">Used in meta description, Open Graph, llms.txt. Keep under 160 chars.</div>
  </div>
</div>

<div class="card">
  <div class="card-title">Email (for welcome &amp; receipt emails)</div>
  <div class="fr">
    <div class="fg">
      <label>From email <span style="color:#ef4444">*</span></label>
      <input type="email" name="from_email" required placeholder="noreply@yourdomain.com">
    </div>
    <div class="fg">
      <label>From name</label>
      <input type="text" name="from_name" value="Yuga" placeholder="Yuga">
    </div>
  </div>
  <div style="font-size:12px;color:#475569;margin-bottom:12px">SMTP — leave blank to use PHP mail() (works on most cPanel hosts)</div>
  <div class="fr">
    <div class="fg">
      <label>SMTP host</label>
      <input type="text" name="smtp_host" placeholder="mail.yourdomain.com">
    </div>
    <div class="fg">
      <label>SMTP port</label>
      <input type="number" name="smtp_port" value="587">
    </div>
  </div>
  <div class="fr">
    <div class="fg">
      <label>SMTP username</label>
      <input type="text" name="smtp_user" placeholder="noreply@yourdomain.com">
    </div>
    <div class="fg">
      <label>SMTP password</label>
      <input type="password" name="smtp_pass" placeholder="(optional)">
    </div>
  </div>
</div>

<div class="card">
  <div class="card-title">AI backend (optional — for SmartChat)</div>
  <div class="fg">
    <label>LLM backend</label>
    <select name="llm_backend" id="llm_be" onchange="showLLM(this.value)">
      <option value="claude">Claude (Anthropic) — recommended</option>
      <option value="openai">OpenAI (ChatGPT)</option>
      <option value="ollama">Ollama (local / self-hosted)</option>
    </select>
    <div class="hint">Yuga works without any LLM — this powers the optional SmartChat feature only.</div>
  </div>
  <div id="llm-claude" class="fg">
    <label>Anthropic API key</label>
    <input type="password" name="anthropic_api_key" placeholder="sk-ant-...">
    <div class="hint">Get it at <strong>console.anthropic.com</strong></div>
  </div>
  <div id="llm-openai" class="fg" style="display:none">
    <label>OpenAI API key</label>
    <input type="password" name="openai_api_key" placeholder="sk-...">
  </div>
  <div id="llm-ollama" class="fg" style="display:none">
    <label>Ollama URL</label>
    <input type="text" name="ollama_url" value="http://localhost:11434">
  </div>
</div>

<div class="card">
  <div class="card-title">Payments (optional — add keys later in config.php)</div>
  <div class="fr">
    <div class="fg">
      <label>Stripe secret key</label>
      <input type="password" name="stripe_key" placeholder="sk_test_... or sk_live_...">
      <div class="hint">dashboard.stripe.com</div>
    </div>
    <div class="fg">
      <label>PayPal client ID</label>
      <input type="text" name="paypal_id" placeholder="from developer.paypal.com">
    </div>
  </div>
  <div class="fg">
    <label>PayPal client secret</label>
    <input type="password" name="paypal_secret" placeholder="(optional)">
  </div>
</div>

<div style="display:flex;gap:10px;align-items:center">
  <button type="submit" class="btn bp">Install Yuga →</button>
  <a href="?restart=1" class="btn bs">← Back</a>
</div>
</form>

<!-- ═══════════════════════════════════════════════════════ STEP 3 -->
<?php elseif ($step === 3): ?>
<div class="card" style="border-color:#14532d;text-align:center">
  <div class="big-ok">🎉</div>
  <h2 style="color:#86efac;font-size:22px;margin-bottom:8px">Yuga is installed!</h2>
  <p style="color:#64748b;font-size:14px;margin-bottom:24px">config.php has been written. Your admin panel is secured and ready.</p>

  <div style="text-align:left">
    <div style="font-size:12px;color:#64748b;font-weight:600;margin-bottom:8px">YOUR URLS</div>
    <div style="font-size:12px;color:#64748b;margin-bottom:4px">Admin panel</div>
    <?php $final_slug = $_SESSION['install_slug'] ?? 'admin'; $final_admin_url = $host . $base . '/' . $final_slug . '/'; ?>
    <div class="url-box"><?= htmlspecialchars($final_admin_url) ?></div>
    <?php if ($final_slug !== 'admin'): ?>
    <div style="font-size:11px;color:#f59e0b;margin-bottom:8px">⚠️ Bookmark this URL — direct /admin/ access is now blocked.</div>
    <?php endif; ?>
    <div style="font-size:12px;color:#64748b;margin-bottom:4px">API endpoint</div>
    <div class="url-box"><?= htmlspecialchars($api_url) ?></div>
    <div style="font-size:12px;color:#64748b;margin-bottom:4px">Customer portal</div>
    <div class="url-box"><?= htmlspecialchars($portal_url) ?></div>
    <div style="font-size:12px;color:#64748b;margin-bottom:4px">Widget embed snippet</div>
    <div class="url-box">&lt;script src="<?= htmlspecialchars($widget_url) ?>" data-api="<?= htmlspecialchars($api_url) ?>" data-model="default" data-auto-learn="true"&gt;&lt;/script&gt;</div>
  </div>

  <div style="margin-top:24px;display:flex;gap:10px;justify-content:center">
    <a href="<?= htmlspecialchars($admin_url) ?>" class="btn bp">Open Admin Panel →</a>
  </div>
</div>

<div class="card" style="border-color:#7f1d1d">
  <div style="display:flex;align-items:center;gap:10px">
    <span style="font-size:24px">🗑️</span>
    <div>
      <div style="font-weight:600;color:#f87171;margin-bottom:4px">Delete install.php now</div>
      <div style="font-size:13px;color:#94a3b8">This file contains your setup form. Remove it from your server via File Manager or FTP to prevent anyone from overwriting your config.</div>
    </div>
  </div>
</div>
<?php endif; ?>

</div><!-- /wrap -->

<?php if (isset($_GET['restart'])) { $_SESSION['install_step'] = 1; header('Location: install.php'); exit; } ?>

<script>
function tog(id) {
  var i = document.getElementById(id);
  i.type = i.type === 'password' ? 'text' : 'password';
}
function showLLM(v) {
  ['claude','openai','ollama'].forEach(function(k){
    var el = document.getElementById('llm-'+k);
    if (el) el.style.display = k === v ? 'block' : 'none';
  });
}
</script>
</body>
</html>
