<div class="p-4 space-y-4">
    <div class="flex items-center gap-2 text-info-600 font-bold">
        <x-heroicon-o-sparkles class="w-5 h-5"/>
        <span>Generated by YG-AI Core</span>
    </div>
    
    <div class="prose prose-sm dark:prose-invert max-w-none bg-info-50 dark:bg-info-900/20 p-4 rounded-xl border border-info-200 dark:border-info-800">
        {!! nl2br(e($summary)) !!}
    </div>

    <div class="text-[10px] text-gray-500 italic">
        Powered by YugaLM SLM &bull; Privacy Protected &bull; Local Processing
    </div>
</div>
