<?php

namespace App\Filament\Resources\CollectForms\Schemas;

use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\Builder;
use Filament\Forms\Components\Builder\Block;
use Filament\Forms\Components\Select;
use Filament\Schemas\Schema;

class CollectFormForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Select::make('project_id')
                    ->relationship('project', 'name')
                    ->required(),
                TextInput::make('title')
                    ->required()
                    ->maxLength(255),
                \Filament\Forms\Components\Section::make('Settings')
                    ->description('Configure how this form behaves.')
                    ->schema([
                        \Filament\Forms\Components\Toggle::make('settings.e2e_enabled')
                            ->label('Enable End-to-End Encryption')
                            ->helperText('Sensitive data will be encrypted in the browser and can only be decrypted with your master key.')
                            ->default(false),
                        Select::make('status')
                            ->options([
                                'draft' => 'Draft',
                                'published' => 'Published',
                                'archived' => 'Archived',
                            ])
                            ->default('draft')
                            ->required(),
                    ])
                    ->columns(2),
                
                \Filament\Forms\Components\Section::make('Form Structure')
                    ->description('Design your data collection form using the blocks below.')
                    ->headerActions([
                        \Filament\Forms\Components\Actions\Action::make('ai_generate')
                            ->label('Magic Generate (AI)')
                            ->icon('heroicon-m-sparkles')
                            ->form([
                                TextInput::make('prompt')
                                    ->label('What kind of data do you want to collect?')
                                    ->placeholder('e.g. A survey for local farmers about crop yield and water access')
                                    ->required(),
                            ])
                            ->action(function (array $data, \Filament\Forms\Set $set) {
                                // Mock AI Logic for demonstration
                                $mockForms = [
                                    'farmers' => [
                                        ['type' => 'text_input', 'data' => ['label' => 'Farmer Name', 'name' => 'farmer_name', 'required' => true]],
                                        ['type' => 'select', 'data' => ['label' => 'Main Crop', 'name' => 'main_crop', 'options' => [['option_label' => 'Rice', 'option_value' => 'rice'], ['option_label' => 'Wheat', 'option_value' => 'wheat']], 'required' => true]],
                                        ['type' => 'gps', 'data' => ['label' => 'Farm Location', 'name' => 'farm_loc', 'required' => true]],
                                    ],
                                    'health' => [
                                        ['type' => 'text_input', 'data' => ['label' => 'Patient Age', 'name' => 'age', 'required' => true]],
                                        ['type' => 'textarea', 'data' => ['label' => 'Symptoms', 'name' => 'symptoms', 'required' => true]],
                                        ['type' => 'photo', 'data' => ['label' => 'Prescription Photo', 'name' => 'rx_photo', 'required' => false]],
                                    ]
                                ];

                                $result = str_contains(strtolower($data['prompt']), 'farm') ? $mockForms['farmers'] : $mockForms['health'];
                                
                                $set('schema', $result);
                                
                                \Filament\Notifications\Notification::make()
                                    ->title('Form generated by YG AI!')
                                    ->success()
                                    ->send();
                            })
                    ])
                    ->schema([
                        Builder::make('schema')
                            ->label('Form Fields')
                            ->blocks([
                                Block::make('text_input')
                                    ->label('Short Text')
                                    ->icon('heroicon-o-chat-bubble-bottom-center-text')
                                    ->schema([
                                        TextInput::make('label')->required(),
                                        TextInput::make('name')->required()->alpha_dash(),
                                        \Filament\Forms\Components\Toggle::make('required'),
                                    ]),
                                Block::make('textarea')
                                    ->label('Long Text')
                                    ->icon('heroicon-o-document-text')
                                    ->schema([
                                        TextInput::make('label')->required(),
                                        TextInput::make('name')->required()->alpha_dash(),
                                        \Filament\Forms\Components\Toggle::make('required'),
                                    ]),
                                Block::make('select')
                                    ->label('Select Dropdown')
                                    ->icon('heroicon-o-list-bullet')
                                    ->schema([
                                        TextInput::make('label')->required(),
                                        TextInput::make('name')->required()->alpha_dash(),
                                        \Filament\Forms\Components\Repeater::make('options')
                                            ->schema([
                                                TextInput::make('option_label')->required(),
                                                TextInput::make('option_value')->required(),
                                            ])
                                            ->columns(2),
                                        \Filament\Forms\Components\Toggle::make('required'),
                                    ]),
                                Block::make('gps')
                                    ->label('GPS Location')
                                    ->icon('heroicon-o-map-pin')
                                    ->schema([
                                        TextInput::make('label')->required(),
                                        TextInput::make('name')->required()->alpha_dash(),
                                        \Filament\Forms\Components\Toggle::make('required'),
                                    ]),
                                Block::make('photo')
                                    ->label('Photo Capture')
                                    ->icon('heroicon-o-camera')
                                    ->schema([
                                        TextInput::make('label')->required(),
                                        TextInput::make('name')->required()->alpha_dash(),
                                        \Filament\Forms\Components\Toggle::make('required'),
                                    ]),
                            ])
                            ->collapsible()
                            ->collapsed()
                            ->cloneable()
                    ]),
            ]);
    }
}
